apiVersion: v1
kind: Service
metadata:
  name: service-ricxapp-{{ .Release.Name }}-rmr
  labels:
    app: {{ .Release.Name }}
spec:
  publishNotReadyAddresses: true
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: rmr
      port: {{ .Values.xapp.rmrPort }}
      targetPort: {{ .Values.xapp.rmrPort }}
      protocol: TCP
    - name: http
      port: {{ .Values.xapp.httpPort }}
      targetPort: {{ .Values.xapp.httpPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-ricxapp-{{ .Release.Name }}-http
  labels:
    app: {{ .Release.Name }}
    monitoring: "true"
spec:
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.xapp.httpPort }}
      targetPort: {{ .Values.xapp.httpPort }}
      protocol: TCP
