apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: nmi
  namespace: default
  annotations:
    oran.unb.br/site: nmi
    oran.unb.br/architecture: amd64
    oran.unb.br/xapp-node: oran-k8s-w02
    oran.unb.br/xapp-image: docker.io/x0tok/oran-xapps@sha256:752c9edc56b8644c78a1fc81d1106d0c34e02a55b48b58f880eaaf3240519a71
    oran.unb.br/e2-node-id: gnbd_001_001_00019b_e2
    oran.unb.br/kpm-metric: DRB.UEThpDl
  labels:
    nephio.org/site-type: laboratory
    nephio.org/region: nmi
spec:
  clusterName: nmi
  cnis:
    - flannel
    - multus
    - ovs-cni
---
apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: cic
  namespace: default
  annotations:
    oran.unb.br/site: cic
    oran.unb.br/architecture: arm64
    oran.unb.br/xapp-node: cic-k8s-w01
    oran.unb.br/xapp-image: pending-arm64-image
    oran.unb.br/e2-node-id: pending-cic-e2-node
    oran.unb.br/kpm-metric: DRB.UEThpDl
  labels:
    nephio.org/site-type: laboratory
    nephio.org/region: cic
spec:
  clusterName: cic
  cnis:
    - flannel
    - multus
    - ovs-cni
