apiVersion: v1
kind: Service
metadata:
  name: service-ricxapp-r4-simple-mon-rmr
  labels:
    app: r4-simple-mon
    app.kubernetes.io/name: r4-simple-mon
    app.kubernetes.io/managed-by: Nephio
    nephio.org/site: nmi
spec:
  publishNotReadyAddresses: true
  selector:
    app: r4-simple-mon
    release: r4-simple-mon
  ports:
    - name: rmr
      port: 4561
      targetPort: 4561
      protocol: TCP
    - name: http
      port: 8091
      targetPort: 8091
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-ricxapp-r4-simple-mon-http
  labels:
    app: r4-simple-mon
    monitoring: "true"
    app.kubernetes.io/name: r4-simple-mon
    app.kubernetes.io/managed-by: Nephio
    nephio.org/site: nmi
spec:
  selector:
    app: r4-simple-mon
    release: r4-simple-mon
  ports:
    - name: http
      port: 8091
      targetPort: 8091
      protocol: TCP
