apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata:
  name: workload-cluster
  annotations:
    config.kubernetes.io/local-config: "true"
    kpt.dev/config-injection: required
    oran.unb.br/site: nmi
    oran.unb.br/architecture: amd64
    oran.unb.br/xapp-node: oran-k8s-w02
    oran.unb.br/xapp-image: docker.io/x0tok/oran-xapps@sha256:752c9edc56b8644c78a1fc81d1106d0c34e02a55b48b58f880eaaf3240519a71
    oran.unb.br/e2-node-id: gnbd_001_001_00019b_e2
    oran.unb.br/kpm-metric: DRB.UEThpDl
    oran.unb.br/rmr-flags: "0"
    oran.unb.br/e2mgr-uri: http://ric-e2mgr.near-rt-ric:3800/v1/nodeb/states
    oran.unb.br/xapp-name: r4-simple-mon
    oran.unb.br/xapp-ip: service-ricxapp-r4-simple-mon-rmr.ricxapp
    oran.unb.br/xapp-rmr-endpoint: service-ricxapp-r4-simple-mon-rmr.ricxapp:4561
    oran.unb.br/xapp-http-endpoint: service-ricxapp-r4-simple-mon-http.ricxapp:8091
    oran.unb.br/xapp-advertised-rmr-port: "4561"
    oran.unb.br/xapp-advertised-http-port: "8091"
    oran.unb.br/submgr-uri: http://ric-submgr.near-rt-ric:8088/ric/v1
    oran.unb.br/appmgr-register-uri: http://ric-appmgr.near-rt-ric:8080/ric/v1/register
spec:
  clusterName: nmi
  cnis:
    - flannel
    - multus
    - ovs-cni
